spring.datasource.url=jdbc:postgresql://bus_booking_system_user:y3AWDU0J9b5WE7N5CC7if2SFWhszax0D@dpg-d09ta7re5dus73c7t6ng-a/bus_booking_system
spring.datasource.username=bus_booking_system_user
spring.datasource.password=y3AWDU0J9b5WE7N5CC7if2SFWhszax0D
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.main.allow-bean-definition-overriding=true
server.port=8082
jwt.secret=kX9#mP$vL2jWqR5tY8uZ3hN6bF0dJ4gH7iK1lM
spring.datasource.driver-class-name=org.postgresql.Driver
